### ISSUE TITLE
Minimum Version in README Should be 1.9.0

### ISSUE THREAD

**Issue by borgmaan** [sellorm/commit-hash-shiny#2]
@sellorm  -- thanks for putting together this example. Just a note that `CONNECT_CONTENT_GUID` was not released until [version 1.9.0](https://docs.rstudio.com/connect/news/#rstudio-connect-190). Thought I'd drop a note in case others are referred here as an example.

**Comment by sellorm** [comment]
Good catch @borgman! Fixed now.

Apologies for any inconvenience.
